### ISSUE TITLE
Final Countdown

### ISSUE THREAD

**Issue by JBBeaulieu** [nooksack-indian-tribe/CurvyLapseRate#2]
- [x] Figure 1

- [x] Figure 2: stick with 2016? only year with ground temperature. Erase first day of NFN7. 

- [x] Fix figure 3: curved lines between sites? move legend box.  "T" in temperature. X-axis!! What sites are used to calculate annual average lapse rate? (green line).  Plot two separate? a) May2018, b) annual average. 
- [x] Section 2.2 Lapse Rate calculation description needs to be completed.

**Comment by ChristinaB** [comment]
@NCristea 
Please fork this repository and finalize the code and notebooks needed to create final versions of Figure 3 and FIgure 4 as well as Table 2.  We can do April or July instead of May? TBD

@ChristinaB To Do
- [x] Upload GIS files to HydroShare

- [x] Work with @JBBeaulieu to upload ODM1 daily files to CUAHSI

- [x] @JBBeaulieu  is ODM2 daily data in HydroShare?

- [x] Get Claire and Oliver's feedback

- [x] Submit paper

**Comment by ChristinaB** [comment]
[Lape rate plots.xlsx](https://github.com/nooksack-indian-tribe/CurvyLapseRate/files/3312180/Lape.rate.plots.xlsx)
@NCristea Please see how we designed the plots in this spreadsheet.

- [x] Make a folder for preprocessing notebooks to reuse later by NIT as needed

- [x] Make a new Notebook that reads in complete dataset and makes figures in the paper. 

- [x] Finish Section 2.2

- [x] Read the paper for final proofread.  Add Brian's reference.  

- [x] Christina - send code for NIT headers and footers

Goal is to submit before or on July 1 !!!

**Comment by ChristinaB** [comment]
Should we actually try to fit a curve to these lines?
